name: CI

on:
  push: { branches: main }
  pull_request: { branches: main }
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - run: ruby tracker.rb
    - uses: actions/upload-artifact@v4
      with:
        name: tracking
        path: tracking.yml
