name: CI

on:
  push: { branches: main }
  pull_request: { branches: main }

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      BUNDLE_GEMFILE: .github/ci.gemfile
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - run: bundle exec rake
